import { Typography } from '@mui/material';
import Head from 'next/head'
import Link from 'next/link';
import Box from '@mui/material/Box'
import ReactPlayer from 'react-player'
import Grid from '@mui/material/Grid';

import HomeLayout from '../../layouts/homeLayout'

export default function Watch({ postData }) {
  console.log(postData)
  return (
    <div>
      <Head>
        <title>Indictos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <Grid container spacing={2}>
        <Grid item md={8} sx={{pt: "0px"}}>
        <ReactPlayer 
        url='https://firebasestorage.googleapis.com/v0/b/indictos-com.appspot.com/o/Big_Buck_Bunny_360_10s_1MB.mp4?alt=media&token=2ba042a6-9954-4b6f-aa9f-e6101c338570' 
        controls={true} 
        pip={true} 
        stopOnUnmount={false} 
        width="100%" 
        height="100%"
        config={{ 
          file: { 
            attributes: {
              controlsList: 'nodownload'
            } 
          } 
        }}
        />
        <Box sx={{p: 2}}>
        <Typography variant='subtitle2'>{postData}</Typography>
        </Box>
        </Grid>
        <Grid item md={4}>
          
        </Grid>
      </Grid>
      </HomeLayout>
    </div>
  )
}

export async function getStaticPaths() {
  return {
    paths: [
      // String variant:
      '/watch/1',
      // Object variant:
      { params: { id: '2' } },
    ],
    fallback: true,
  }
}

export async function getStaticProps({ params }) {
  const postData = params.id
  return {
    props: {
      postData
    }
  }
}
