import React, { useState, useEffect } from "react";
import Head from "next/head";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import List from "@mui/material/List";
import Link from "next/link";

import HomeLayout from "../../layouts/homeLayout";
import { Button, TextField, Typography } from "@mui/material";
import fb from "../../firebase/clientApp";
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";
import {
  getFirestore,
  collection,
  onSnapshot,
  query,
  orderBy,
  QuerySnapshot,
} from "firebase/firestore";
import MovieListItem from "../../components/movieListItem";

const auth = getAuth(fb);
const db = getFirestore();

export default function Movies() {
  const [movies, setMovies] = useState([]);
  useEffect(() => {
    const collectionRef = collection(db, "movies");
    const q = query(collectionRef, orderBy("created", "desc"));
    const getMovies = onSnapshot(q, (QuerySnapshot) => {
      setMovies(
        QuerySnapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id }))
      );
    });
    return getMovies;
  }, []);
  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
        <Box sx={{ p: 2 }}>
          <Typography variant="h1" component="div" gutterBottom>
            Movies
          </Typography>
          <TextField
            id="addMovieTitle"
            label="Add Movie Title"
            variant="outlined"
            fullWidth
            margin="dense"
          />
          <TextField
            id="addMovieDescription"
            label="Add Movie Description"
            variant="outlined"
            multiline
            maxRows={4}
            fullWidth
            margin="dense"
          />
          <Button variant="contained" margin="dense">
            Add Movie
          </Button>
          {movies && (
            <List>
              {movies.map((m) => (
                <Link href={"/movies/" + m.id} key={m.id}>
                  <a>
                    <h3>{m.title}</h3>
                  </a>
                </Link>
              ))}
            </List>
          )}
        </Box>
      </HomeLayout>
    </div>
  );
}
