import Head from "next/head";
import styles from "../styles/Home.module.css";
import IndexAppbar from "../components/indexAppbar";
import IndexLeadPanel from "../components/indexLeadPanel";
import HomeScreen from "../components/homeScreen";
import HomeLayout from "../layouts/homeLayout";
import Box from "@mui/material/Box";
import AboutMD from "../markdowns/about.mdx";
import PlainLayout from "../layouts/plainLayout";
import { Container, Typography } from "@mui/material";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlainLayout>
        <Container maxWidth="md" sx={{ py: 3 }}>
          <Typography variant="h3" gutterBottom>
            About
          </Typography>
          <AboutMD />
        </Container>
      </PlainLayout>
    </div>
  );
}
