import Head from 'next/head'
import styles from '../styles/Home.module.css'
import IndexAppbar from '../components/indexAppbar'
import IndexLeadPanel from '../components/indexLeadPanel'
import HomeScreen from '../components/homeScreen'
import Box from '@mui/material/Box'
import Grid from '@mui/material/Grid';
import HomeLayout from '../layouts/homeLayout'
import MandiSection from '../components/mandiSection'
import BulbuleSection from '../components/bulbuleSection'
import ParasyticalSection from '../components/parasyticalSection'
import { Button, TextField, Typography } from '@mui/material'

export default function AddMovie() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Add a movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <Box sx={{p: 2}}>
      <Typography variant="h1" component="div" gutterBottom>
        Add Movie
      </Typography>
      <TextField id="addMovieTitle" label="Add Movie Title" variant="outlined" fullWidth margin="dense"/>
      <TextField id="addMovieDescription" 
      label="Add Movie Description" 
      variant="outlined" 
      multiline
        maxRows={4} fullWidth margin="dense"/>
      <Button variant="contained" margin="dense">Add Movie</Button>

      </Box>
      
      </HomeLayout>
    </div>
  )
}
