import Head from "next/head";
import styles from "../styles/Home.module.css";
import IndexAppbar from "../components/indexAppbar";
import IndexLeadPanel from "../components/indexLeadPanel";
import HomeScreen from "../components/homeScreen";
import HomeLayout from "../layouts/homeLayout";
import Box from "@mui/material/Box";
import ContactMD from "../markdowns/contact.mdx";
import ContactForm from "../components/contactForm";
import PlainLayout from "../layouts/plainLayout";
import { Container, Typography } from "@mui/material";

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlainLayout>
        <Container maxWidth="md" sx={{ py: 3 }}>
          <Typography variant="h3" gutterBottom>
            Contact
          </Typography>
          <Box
            sx={{
              textAlign: "center",
              justifyItems: "center",
            }}
          >
            <ContactMD />
            <ContactForm />
          </Box>
        </Container>
      </PlainLayout>
    </div>
  );
}
