import Head from 'next/head'
import styles from '../styles/Home.module.css'
import IndexAppbar from '../components/indexAppbar'
import IndexLeadPanel from '../components/indexLeadPanel'
import HomeScreen from '../components/homeScreen'
import HomeLayout from '../layouts/homeLayout'
import Box from '@mui/material/Box'
import ContactMD from '../markdowns/contact.mdx'
import ContactForm from '../components/contactForm'

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <Box sx={{p: 2}}><ContactMD />
      <ContactForm />
      </Box>
      </HomeLayout>
    </div>
  )
}
