import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomeLayout from '../layouts/homeLayout'
import FaqMD from '../markdowns/faq.mdx'

export default function Faq() {
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Privacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <FaqMD />
      </HomeLayout>
    </div>
  )
}