import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomeLayout from "../layouts/homeLayout";
import Box from "@mui/material/Box";
import FaqMD from "../markdowns/faq.mdx";

import PlainLayout from "../layouts/plainLayout";
import { Container, Typography } from "@mui/material";

export default function Faq() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlainLayout>
        <Container maxWidth="md" sx={{ py: 5 }}>
          <Typography align="center" variant="h3" gutterBottom>
            FAQ
          </Typography>
          <FaqMD />
        </Container>
      </PlainLayout>
    </div>
  );
}
