import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomeLayout from '../layouts/homeLayout'
import RecommendedVideoSection from '../components/recommendedVideoSection'
import InvestCta from '../components/investCta'
import IndexMovieCover from '../components/indexMovieCover'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Indictos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
        <RecommendedVideoSection />
      </HomeLayout>
    </div>
  )
}
