import Head from 'next/head'
import styles from '../styles/Home.module.css'
import IndexAppbar from '../components/indexAppbar'
import IndexLeadPanel from '../components/indexLeadPanel'
import HomeScreen from '../components/homeScreen'
import Box from '@mui/material/Box'
import HomeLayout from '../layouts/homeLayout'
import MandiSection from '../components/mandiSection'

export default function Invest() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Invest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <Box>
      <MandiSection />
      </Box>
      
      </HomeLayout>
    </div>
  )
}
