import Head from 'next/head'
import styles from '../styles/Home.module.css'
import IndexAppbar from '../components/indexAppbar'
import IndexLeadPanel from '../components/indexLeadPanel'
import HomeScreen from '../components/homeScreen'
import Box from '@mui/material/Box'
import Grid from '@mui/material/Grid';
import HomeLayout from '../layouts/homeLayout'
import MandiSection from '../components/mandiSection'
import BulbuleSection from '../components/bulbuleSection'
import ParasyticalSection from '../components/parasyticalSection'

export default function Invest() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Invest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <Box>
      <Grid container spacing={2}>
  <Grid item xs={12} md={4}>
  <BulbuleSection />
  </Grid>
  <Grid item xs={12} md={4}>
  <MandiSection />
  </Grid>
  <Grid item xs={12} md={4}>
  <ParasyticalSection />
  </Grid>
</Grid>
      
      </Box>
      
      </HomeLayout>
    </div>
  )
}
