import Head from 'next/head'
import styles from '../styles/Home.module.css'
import IndexAppbar from '../components/indexAppbar'
import IndexLeadPanel from '../components/indexLeadPanel'
import HomeScreen from '../components/homeScreen'
import Box from '@mui/material/Box'
import HomeLayout from '../layouts/homeLayout'

export default function Premium() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Premium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <Box sx={{p: 2}}>Premium</Box>
      </HomeLayout>
    </div>
  )
}
