import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Box from '@mui/material/Box';
import IndexAppbar from '../components/indexAppbar'
import IndexLeadPanel from '../components/indexLeadPanel'
import HomeScreen from '../components/homeScreen'
import HomeLayout from '../layouts/homeLayout'
import { Typography } from '@mui/material'

export default function Subscriptions() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Subscriptions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
      <Box sx={{p: 2}}>
      <Typography variant='body1'>You didn&apos;t subscribe yet! Please subscribe and start your journey with us.</Typography>
      </Box>
      
      </HomeLayout>
    </div>
  )
}
